version: '2'
services:
  classschedule-app:
    image: classschedule
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://classschedule.c3lss5mugejc.eu-west-1.rds.amazonaws.com:5432/classschedule
      - JHIPSTER_SLEEP=10 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  classschedule-postgresql:
    extends:
      file: postgresql.yml
      service: classschedule-postgresql
