version: '2'
services:
  classschedule-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/classschedule/postgresql/:/var/lib/postgresql/data/
    environment:
     - POSTGRES_USER=classschedule
     - POSTGRES_PASSWORD=classschedule
     - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - 5432:5432
